### ISSUE TITLE
Add Meson Examples

### ISSUE THREAD

**Issue by wdhowe** [wdhowe/meson#11]
- [ ] Add Port of Standard Java Example - issue #12 
- [ ] Add Port of Java Exception Framework Example - #13
- [ ] Add Port of Hello World Mesomatic Example - #14
- [ ] Add Port of Framework with No Executor Example - #15
- [ ] Add Port of Docker Framework Example - #16

Part of epic #2
