### ISSUE TITLE
Deliver Clojure Client for v1.0 Mesos HTTP APIs

### ISSUE THREAD

**Issue by wdhowe** [wdhowe/meson#2]
Milestones originally copied from upstream [clojusc/meson issues](https://github.com/clojusc/meson/issues). Modifications have been made as needed.

**Milestone 0.1.0 - Complete**

- [x] Setup testing infrastructure - [issue 40 (from clojusc/meson)](https://github.com/clojusc/meson/issues/40)
- [x] Add project documentation - [issue 65 (from clojusc/meson)](https://github.com/clojusc/meson/issues/65)
- [x] Reorganize existing protobufs into modular namespaces - [issue 29 (from clojusc/meson)](https://github.com/clojusc/meson/issues/29)
- [x] Add HTTP verb wrappers- [issue 24 (from clojusc/meson)](https://github.com/clojusc/meson/issues/24)
- [x] Update namespaces for Meson Client, Scheduler, and Executor APIs - [issue 49 (from clojusc/meson)](https://github.com/clojusc/meson/issues/49)
- [x] Support API event streams - [issue 56 (from clojusc/meson)](https://github.com/clojusc/meson/issues/56)
- [x] Implement v1.0 Scheduler API - [issue 4 (from clojusc/meson)](https://github.com/clojusc/meson/issues/4)

**Milestone 0.2.0**

- [ ] Implement v1.0 Operator API - issue #3 

**Milestone 0.3.0**

- [ ] Implement v1.0 Executor API - issue #7 

**Milestone 1.0.0**

- [ ] Add Meson Examples - issue #11
