### ISSUE TITLE
Implement v1.0 Operator API

### ISSUE THREAD

**Issue by wdhowe** [wdhowe/meson#3]
Official docs are here: http://mesos.apache.org/documentation/latest/operator-http-api/

SubTasks:

- [x] Implement Common Operator Calls - issue #4 
- [ ] Implement Master/Agent Operator Calls - issue #5
- [ ] Provide Default Handler for Operator Events - issue #6

Part of epic #2
