### ISSUE TITLE
Implement v1.0 Executor API

### ISSUE THREAD

**Issue by wdhowe** [wdhowe/meson#7]
http://mesos.apache.org/documentation/latest/executor-http-api/

- [ ] Implement Executor Calls - issue #8 
- [ ] Provide Default Handler for Executor Events - issue #9 
- [ ] Implement Executor Environment Variables - issue #10

Part of epic #2
